name: Build PVE Kernel package

on:
  workflow_dispatch:
    inputs:
      ZFS_SHA1:
        description: 'ZFS SHA1'
        required: true
      KERNEL_SHA1:
        description: 'Kernel SHA1'
        required: true

jobs:
  build:
    runs-on: pve-runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Prepare build
      run: |
        make prep ZFS_SHA1=${{ github.event.inputs.ZFS_SHA1 }} KERNEL_SHA1=${{ github.event.inputs.KERNEL_SHA1 }}

    - name: Compile the package
      run: |
        make deb ZFS_SHA1=${{ github.event.inputs.ZFS_SHA1 }} KERNEL_SHA1=${{ github.event.inputs.KERNEL_SHA1 }}

    - name: Upload .deb, .buildinfo, and .changes files as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-packages
        path: |
          *.deb
          *.buildinfo
          *.changes
