name: Prepare build environment and cache it

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  setup-env:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
    - name: Setup container environment
      run: |
        apt-get update
        apt-get install -y git gh

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # Add Proxmox APT repository
    - name: Add Proxmox repository to sources.list
      run: |
        echo "deb http://download.proxmox.com/debian/devel/ bookworm main" >> /etc/apt/sources.list
        wget https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg 
        sha512sum /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg 
        7da6fe34168adc6e479327ba517796d4702fa2f8b4f0a9833f5ea6e6b48f6507a6da403a274fe201595edc86a84463d50383d07f64bdde2e3658108db7d6dc87 /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg 

    # Cache apt packages
    - name: Cache apt packages
      uses: actions/cache@v2
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/debian/control') }}

    # Install necessary packages
    - name: Setup build environment
      run: |
        apt-get update
        apt-get install -y build-essential git git-email debhelper pve-doc-generator devscripts python-is-python3 dh-python sphinx-common quilt libtraceevents-dev libunwind-dev libzstd-dev png-config equivs

    # Execute mk-build-deps
    - name: Execute mk-build-deps for control files
      run: |
        mk-build-deps -ir proxmox-kernel-*/debian/control
        mk-build-deps -ir proxmox-kernel-*/modules/pkg-zfs/debian/control

    # Cache the submodules
    - name: Cache submodules
      uses: actions/cache@v2
      with:
        path: submodules/
        key: ${{ runner.os }}-submodules-${{ hashFiles('.gitmodules') }}